name: testing
description: "GraphQL dummy app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Just to format the Date in every category.
  intl: ^0.19.0

  # GraphQL package I used.
  graphql_flutter: ^5.1.2

  # Handling State Management with Provider.
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
